# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{webtagger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lfborjas"]
  s.date = %q{2010-08-28}
  s.description = %q{Use webtagger to hace easy access to keyword extraction web services (tagthe.net, yahoo and alchemy)}
  s.email = %q{me@lfborjas.com}
  s.executables = ["webtagger", "webtagger"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/webtagger",
     "lib/httparty_icebox.rb",
     "lib/webtagger.rb",
     "test/helper.rb",
     "test/test_webtagger.rb",
     "webtagger.gemspec"
  ]
  s.homepage = %q{http://github.com/lfborjas/webtagger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Use some popular web services to extract keywords from text}
  s.test_files = [
    "test/helper.rb",
     "test/test_webtagger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, ["= 0.6.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<httparty>, ["= 0.6.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<httparty>, ["= 0.6.1"])
  end
end

